import { PokemonTypes } from "@/src/types/pokemon_type"

import { createMoveTable, createPhysicalMove, createSpecialMove, createStatusMove } from "../utils"

export const Move = createMoveTable({
  ACCELEROCK: createPhysicalMove("ACCELEROCK", {
    name: "Accelerock",
    power: 40,
    type: PokemonTypes.ROCK,
    effect: "null",
  }),
  AERIAL_ACE: createPhysicalMove("AERIAL_ACE", {
    name: "Aerial Ace",
    power: 60,
    type: PokemonTypes.FLYING,
    effect: "Never misses.",
  }),
  AIR_SLASH: createSpecialMove("AIR_SLASH", {
    name: "Air Slash",
    power: 75,
    type: PokemonTypes.FLYING,
    effect: "Has a 30% chance to make the target flinch.",
  }),
  AQUA_CUTTER: createPhysicalMove("AQUA_CUTTER", {
    name: "Aqua Cutter",
    power: 70,
    type: PokemonTypes.WATER,
    effect: "null",
  }),
  AQUA_JET: createPhysicalMove("AQUA_JET", {
    name: "Aqua Jet",
    power: 40,
    type: PokemonTypes.WATER,
    effect: "null",
  }),
  AQUA_STEP: createPhysicalMove("AQUA_STEP", {
    name: "Aqua Step",
    power: 80,
    type: PokemonTypes.WATER,
    effect: "null",
  }),
  AQUA_TAIL: createPhysicalMove("AQUA_TAIL", {
    name: "Aqua Tail",
    power: 90,
    type: PokemonTypes.WATER,
    effect: "null",
  }),
  ARM_THRUST: createPhysicalMove("ARM_THRUST", {
    name: "Arm Thrust",
    power: 15,
    type: PokemonTypes.FIGHTING,
    effect: "Hits 2-5 times in one turn.",
  }),
  ASSURANCE: createPhysicalMove("ASSURANCE", {
    name: "Assurance",
    power: 60,
    type: PokemonTypes.DARK,
    effect: "Power is doubled if the target has already received damage this turn.",
  }),
  AURA_SPHERE: createSpecialMove("AURA_SPHERE", {
    name: "Aura Sphere",
    power: 80,
    type: PokemonTypes.FIGHTING,
    effect: "Never misses.",
  }),
  AURORA_BEAM: createSpecialMove("AURORA_BEAM", {
    name: "Aurora Beam",
    power: 65,
    type: PokemonTypes.ICE,
    effect: "Has a 10% chance to lower the target's Attack by one stage.",
  }),
  AURORA_VEIL: createStatusMove("AURORA_VEIL", {
    name: "Aurora Veil",
    power: null,
    type: PokemonTypes.ICE,
    effect: "Reduces damage five turns, but must be used during hail.",
  }),
  AVALANCHE: createPhysicalMove("AVALANCHE", {
    name: "Avalanche",
    power: 60,
    type: PokemonTypes.ICE,
    effect: "Inflicts double damage if the user takes damage before attacking this turn.",
  }),
  BABY_DOLL_EYES: createStatusMove("BABY_DOLL_EYES", {
    name: "Baby-Doll Eyes",
    power: null,
    type: PokemonTypes.FAIRY,
    effect: "Lowers the target's Attack by one stage.",
  }),
  BITE: createPhysicalMove("BITE", {
    name: "Bite",
    power: 60,
    type: PokemonTypes.DARK,
    effect: "Has a 30% chance to make the target flinch.",
  }),
  BLAZING_TORQUE: createPhysicalMove("BLAZING_TORQUE", {
    name: "Blazing Torque",
    power: 80,
    type: PokemonTypes.FIRE,
    effect: "null",
  }),
  BLIZZARD: createSpecialMove("BLIZZARD", {
    name: "Blizzard",
    power: 110,
    type: PokemonTypes.ICE,
    effect: "Has a 10% chance to freeze the target.",
  }),
  BLOCK: createStatusMove("BLOCK", {
    name: "Block",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Prevents the target from leaving battle.",
  }),
  BODY_PRESS: createPhysicalMove("BODY_PRESS", {
    name: "Body Press",
    power: 80,
    type: PokemonTypes.FIGHTING,
    effect: "null",
  }),
  BODY_SLAM: createPhysicalMove("BODY_SLAM", {
    name: "Body Slam",
    power: 85,
    type: PokemonTypes.NORMAL,
    effect: "Has a 30% chance to paralyze the target.",
  }),
  BOUNCE: createPhysicalMove("BOUNCE", {
    name: "Bounce",
    power: 85,
    type: PokemonTypes.FLYING,
    effect: "User bounces high into the air, dodging all attacks, and hits next turn.",
  }),
  BRAVE_BIRD: createPhysicalMove("BRAVE_BIRD", {
    name: "Brave Bird",
    power: 120,
    type: PokemonTypes.FLYING,
    effect: "User receives 1/3 the damage inflicted in recoil.",
  }),
  BRICK_BREAK: createPhysicalMove("BRICK_BREAK", {
    name: "Brick Break",
    power: 75,
    type: PokemonTypes.FIGHTING,
    effect: "Destroys Reflect and Light Screen.",
  }),
  BUG_BITE: createPhysicalMove("BUG_BITE", {
    name: "Bug Bite",
    power: 60,
    type: PokemonTypes.BUG,
    effect: "If target has a berry, inflicts double damage and uses the berry.",
  }),
  BUG_BUZZ: createSpecialMove("BUG_BUZZ", {
    name: "Bug Buzz",
    power: 90,
    type: PokemonTypes.BUG,
    effect: "Has a 10% chance to lower the target's Special Defense by one stage.",
  }),
  BULK_UP: createStatusMove("BULK_UP", {
    name: "Bulk Up",
    power: null,
    type: PokemonTypes.FIGHTING,
    effect: "Raises the user's Attack and Defense by one stage.",
  }),
  BULLDOZE: createPhysicalMove("BULLDOZE", {
    name: "Bulldoze",
    power: 60,
    type: PokemonTypes.GROUND,
    effect: "Has a 100% chance to lower the target's Speed by one stage.",
  }),
  BULLET_SEED: createPhysicalMove("BULLET_SEED", {
    name: "Bullet Seed",
    power: 25,
    type: PokemonTypes.GRASS,
    effect: "Hits 2-5 times in one turn.",
  }),
  CHARGE_BEAM: createSpecialMove("CHARGE_BEAM", {
    name: "Charge Beam",
    power: 50,
    type: PokemonTypes.ELECTRIC,
    effect: "Has a 70% chance to raise the user's Special Attack by one stage.",
  }),
  CHARGE: createStatusMove("CHARGE", {
    name: "Charge",
    power: null,
    type: PokemonTypes.ELECTRIC,
    effect:
      "Raises the user's Special Defense by one stage.  User's Electric moves have doubled power next turn.",
  }),
  CHARM: createStatusMove("CHARM", {
    name: "Charm",
    power: null,
    type: PokemonTypes.FAIRY,
    effect: "Lowers the target's Attack by two stages.",
  }),
  CLEAR_SMOG: createSpecialMove("CLEAR_SMOG", {
    name: "Clear Smog",
    power: 50,
    type: PokemonTypes.POISON,
    effect: "Removes all of the target's stat modifiers.",
  }),
  CLOSE_COMBAT: createPhysicalMove("CLOSE_COMBAT", {
    name: "Close Combat",
    power: 120,
    type: PokemonTypes.FIGHTING,
    effect: "Lowers the user's Defense and Special Defense by one stage after inflicting damage.",
  }),
  COIL: createStatusMove("COIL", {
    name: "Coil",
    power: null,
    type: PokemonTypes.POISON,
    effect: "Raises the user's Attack, Defense, and accuracy by one stage each.",
  }),
  COMBAT_TORQUE: createPhysicalMove("COMBAT_TORQUE", {
    name: "Combat Torque",
    power: 100,
    type: PokemonTypes.FIGHTING,
    effect: "null",
  }),
  CONFUSE_RAY: createStatusMove("CONFUSE_RAY", {
    name: "Confuse Ray",
    power: null,
    type: PokemonTypes.GHOST,
    effect: "Confuses the target.",
  }),
  CRABHAMMER: createPhysicalMove("CRABHAMMER", {
    name: "Crabhammer",
    power: 100,
    type: PokemonTypes.WATER,
    effect: "Has an increased chance for a critical hit.",
  }),
  CRUNCH: createPhysicalMove("CRUNCH", {
    name: "Crunch",
    power: 80,
    type: PokemonTypes.DARK,
    effect: "Has a 20% chance to lower the target's Defense by one stage.",
  }),
  DARK_PULSE: createSpecialMove("DARK_PULSE", {
    name: "Dark Pulse",
    power: 80,
    type: PokemonTypes.DARK,
    effect: "Has a 20% chance to make the target flinch.",
  }),
  DAZZLING_GLEAM: createSpecialMove("DAZZLING_GLEAM", {
    name: "Dazzling Gleam",
    power: 80,
    type: PokemonTypes.FAIRY,
    effect: "null",
  }),
  DIG: createPhysicalMove("DIG", {
    name: "Dig",
    power: 80,
    type: PokemonTypes.GROUND,
    effect: "User digs underground, dodging all attacks, and hits next turn.",
  }),
  DISCHARGE: createSpecialMove("DISCHARGE", {
    name: "Discharge",
    power: 80,
    type: PokemonTypes.ELECTRIC,
    effect: "Has a 30% chance to paralyze the target.",
  }),
  DOUBLE_HIT: createPhysicalMove("DOUBLE_HIT", {
    name: "Double Hit",
    power: 34,
    type: PokemonTypes.NORMAL,
    effect: "Hits twice in one turn.",
  }),
  DOUBLE_KICK: createPhysicalMove("DOUBLE_KICK", {
    name: "Double Kick",
    power: 30,
    type: PokemonTypes.FIGHTING,
    effect: "Hits twice in one turn.",
  }),
  DOUBLE_SHOCK: createPhysicalMove("DOUBLE_SHOCK", {
    name: "Double Shock",
    power: 120,
    type: PokemonTypes.ELECTRIC,
    effect: "null",
  }),
  DOUBLE_TEAM: createStatusMove("DOUBLE_TEAM", {
    name: "Double Team",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Raises the user's evasion by one stage.",
  }),
  DRAGON_CLAW: createPhysicalMove("DRAGON_CLAW", {
    name: "Dragon Claw",
    power: 80,
    type: PokemonTypes.DRAGON,
    effect: "null",
  }),
  DRAGON_PULSE: createSpecialMove("DRAGON_PULSE", {
    name: "Dragon Pulse",
    power: 85,
    type: PokemonTypes.DRAGON,
    effect: "null",
  }),
  DRAGON_RUSH: createPhysicalMove("DRAGON_RUSH", {
    name: "Dragon Rush",
    power: 100,
    type: PokemonTypes.DRAGON,
    effect: "Has a 20% chance to make the target flinch.",
  }),
  DRAIN_PUNCH: createPhysicalMove("DRAIN_PUNCH", {
    name: "Drain Punch",
    power: 75,
    type: PokemonTypes.FIGHTING,
    effect:
      "The user attacks with an energy-draining punch. The user's HP is restored by up to half the damage taken by the target.",
  }),
  DREAM_EATER: createSpecialMove("DREAM_EATER", {
    name: "Dream Eater",
    power: 100,
    type: PokemonTypes.PSYCHIC,
    effect: "Only works on sleeping Pokémon. Drains half the damage inflicted to heal the user.",
  }),
  DRILL_PECK: createPhysicalMove("DRILL_PECK", {
    name: "Drill Peck",
    power: 80,
    type: PokemonTypes.FLYING,
    effect: "A corkscrewing attack that strikes the target with a sharp beak acting as a drill.",
  }),
  DRILL_RUN: createPhysicalMove("DRILL_RUN", {
    name: "Drill Run",
    power: 80,
    type: PokemonTypes.GROUND,
    effect: "Has an increased chance for a critical hit.",
  }),
  EARTH_POWER: createSpecialMove("EARTH_POWER", {
    name: "Earth Power",
    power: 90,
    type: PokemonTypes.GROUND,
    effect: "Has a 10% chance to lower the target's Special Defense by one stage.",
  }),
  EARTHQUAKE: createPhysicalMove("EARTHQUAKE", {
    name: "Earthquake",
    power: 100,
    type: PokemonTypes.GROUND,
    effect: "Inflicts regular damage and can hit Dig users.",
  }),
  EMBER: createSpecialMove("EMBER", {
    name: "Ember",
    power: 40,
    type: PokemonTypes.FIRE,
    effect: "Has a 10% chance to burn the target.",
  }),
  ENERGY_BALL: createSpecialMove("ENERGY_BALL", {
    name: "Energy Ball",
    power: 90,
    type: PokemonTypes.GRASS,
    effect: "Has a 10% chance to lower the target's Special Defense by one stage.",
  }),
  FACADE: createPhysicalMove("FACADE", {
    name: "Facade",
    power: 70,
    type: PokemonTypes.NORMAL,
    effect: "Power doubles if user is burned, paralyzed, or poisoned.",
  }),
  FAKE_OUT: createPhysicalMove("FAKE_OUT", {
    name: "Fake Out",
    power: 40,
    type: PokemonTypes.NORMAL,
    effect:
      "This attack hits first and makes the target flinch. It works only on the first turn each time the user enters battle. ",
  }),
  FIERY_DANCE: createSpecialMove("FIERY_DANCE", {
    name: "Fiery Dance",
    power: 80,
    type: PokemonTypes.FIRE,
    effect:
      "Cloaked in flames, the user attacks the target by dancing and flapping its wings. This may also boost the user's Sp. Atk stat.",
  }),
  FIRE_BLAST: createSpecialMove("FIRE_BLAST", {
    name: "Fire Blast",
    power: 110,
    type: PokemonTypes.FIRE,
    effect: "Has a 10% chance to burn the target.",
  }),
  FIRE_FANG: createPhysicalMove("FIRE_FANG", {
    name: "Fire Fang",
    power: 65,
    type: PokemonTypes.FIRE,
    effect:
      "Has a 10% chance to burn the target and a $effect_chance% chance to make the target flinch.",
  }),
  FIRE_PUNCH: createPhysicalMove("FIRE_PUNCH", {
    name: "Fire Punch",
    power: 75,
    type: PokemonTypes.FIRE,
    effect: "Has a 10% chance to burn the target.",
  }),
  FIRE_SPIN: createSpecialMove("FIRE_SPIN", {
    name: "Fire Spin",
    power: 35,
    type: PokemonTypes.FIRE,
    effect: "Prevents the target from fleeing and inflicts damage for 2-5 turns.",
  }),
  FLAIL: createPhysicalMove("FLAIL", {
    name: "Flail",
    power: null,
    type: PokemonTypes.NORMAL,
    effect:
      "Inflicts more damage when the user has less HP remaining, with a maximum of 200 power.",
  }),
  FLAME_CHARGE: createPhysicalMove("FLAME_CHARGE", {
    name: "Flame Charge",
    power: 50,
    type: PokemonTypes.FIRE,
    effect: "Inflicts regular damage.  Raises the user's Speed by one stage.",
  }),
  FLAME_WHEEL: createPhysicalMove("FLAME_WHEEL", {
    name: "Flame Wheel",
    power: 60,
    type: PokemonTypes.FIRE,
    effect: "Has a 10% chance to burn the target.  Lets frozen Pokémon thaw themselves.",
  }),
  FLAMETHROWER: createSpecialMove("FLAMETHROWER", {
    name: "Flamethrower",
    power: 90,
    type: PokemonTypes.FIRE,
    effect: "Has a 10% chance to burn the target.",
  }),
  FLARE_BLITZ: createPhysicalMove("FLARE_BLITZ", {
    name: "Flare Blitz",
    power: 120,
    type: PokemonTypes.FIRE,
    effect: "User takes 1/3 the damage inflicted in recoil.  Has a 10% chance to burn the target.",
  }),
  FLASH_CANNON: createSpecialMove("FLASH_CANNON", {
    name: "Flash Cannon",
    power: 80,
    type: PokemonTypes.STEEL,
    effect: "Has a 10% chance to lower the target's Special Defense by one stage.",
  }),
  FLOWER_TRICK: createPhysicalMove("FLOWER_TRICK", {
    name: "Flower Trick",
    power: 70,
    type: PokemonTypes.GRASS,
    effect: "null",
  }),
  FOUL_PLAY: createPhysicalMove("FOUL_PLAY", {
    name: "Foul Play",
    power: 95,
    type: PokemonTypes.DARK,
    effect: "Calculates damage with the target's attacking stat.",
  }),
  FREEZE_DRY: createSpecialMove("FREEZE_DRY", {
    name: "Freeze-Dry",
    power: 70,
    type: PokemonTypes.ICE,
    effect:
      "The user rapidly cools the target. This may also leave the target frozen. This move is super effective on Water types.",
  }),
  FURY_CUTTER: createPhysicalMove("FURY_CUTTER", {
    name: "Fury Cutter",
    power: 40,
    type: PokemonTypes.BUG,
    effect:
      "Power doubles every turn this move is used in succession after the first, maxing out after five turns.",
  }),
  FURY_SWIPES: createPhysicalMove("FURY_SWIPES", {
    name: "Fury Swipes",
    power: 18,
    type: PokemonTypes.NORMAL,
    effect: "Hits 2-5 times in one turn.",
  }),
  FUTURE_SIGHT: createSpecialMove("FUTURE_SIGHT", {
    name: "Future Sight",
    power: 120,
    type: PokemonTypes.PSYCHIC,
    effect: "Hits the target two turns later.",
  }),
  GIGA_DRAIN: createSpecialMove("GIGA_DRAIN", {
    name: "Giga Drain",
    power: 75,
    type: PokemonTypes.GRASS,
    effect: "Drains half the damage inflicted to heal the user.",
  }),
  GIGA_IMPACT: createPhysicalMove("GIGA_IMPACT", {
    name: "Giga Impact",
    power: 150,
    type: PokemonTypes.NORMAL,
    effect:
      "The user charges at the target using every bit of its power. The user can't move on the next turn.",
  }),
  GIGATON_HAMMER: createPhysicalMove("GIGATON_HAMMER", {
    name: "Gigaton Hammer",
    power: 160,
    type: PokemonTypes.STEEL,
    effect: "null",
  }),
  GLAIVE_RUSH: createPhysicalMove("GLAIVE_RUSH", {
    name: "Glaive Rush",
    power: 120,
    type: PokemonTypes.DRAGON,
    effect: "null",
  }),
  GLARE: createStatusMove("GLARE", {
    name: "Glare",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Paralyzes the target.",
  }),
  GROWL: createStatusMove("GROWL", {
    name: "Growl",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Lowers the target's Attack by one stage.",
  }),
  GYRO_BALL: createPhysicalMove("GYRO_BALL", {
    name: "Gyro Ball",
    power: null,
    type: PokemonTypes.STEEL,
    effect: "Power raises when the user has lower Speed, up to a maximum of 150.",
  }),
  HEADBUTT: createPhysicalMove("HEADBUTT", {
    name: "Headbutt",
    power: 70,
    type: PokemonTypes.NORMAL,
    effect: "Has a 30% chance to make the target flinch.",
  }),
  HEAVY_SLAM: createPhysicalMove("HEAVY_SLAM", {
    name: "Heavy Slam",
    power: null,
    type: PokemonTypes.STEEL,
    effect: "Power is higher when the user weighs more than the target, up to a maximum of 120.",
  }),
  HEX: createSpecialMove("HEX", {
    name: "Hex",
    power: 65,
    type: PokemonTypes.GHOST,
    effect: "Has double power if the target has a major status ailment.",
  }),
  HIGH_HORSEPOWER: createPhysicalMove("HIGH_HORSEPOWER", {
    name: "High Horsepower",
    power: 95,
    type: PokemonTypes.GROUND,
    effect: "null",
  }),
  HONE_CLAWS: createStatusMove("HONE_CLAWS", {
    name: "Hone Claws",
    power: null,
    type: PokemonTypes.DARK,
    effect: "Raises the user's Attack and accuracy by one stage.",
  }),
  HORN_LEECH: createPhysicalMove("HORN_LEECH", {
    name: "Horn Leech",
    power: 75,
    type: PokemonTypes.GRASS,
    effect: "Drains half the damage inflicted to heal the user.",
  }),
  HOWL: createStatusMove("HOWL", {
    name: "Howl",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Raises the user's Attack by one stage.",
  }),
  HURRICANE: createSpecialMove("HURRICANE", {
    name: "Hurricane",
    power: 110,
    type: PokemonTypes.FLYING,
    effect: "Has a 30% chance to confuse the target.",
  }),
  HYDRO_PUMP: createSpecialMove("HYDRO_PUMP", {
    name: "Hydro Pump",
    power: 110,
    type: PokemonTypes.WATER,
    effect: "null",
  }),
  HYPER_BEAM: createSpecialMove("HYPER_BEAM", {
    name: "Hyper beam",
    power: 150,
    type: PokemonTypes.NORMAL,
    effect: "The target is attacked with a powerful beam. The user can't move on the next turn.",
  }),
  HYPER_DRILL: createPhysicalMove("HYPER_DRILL", {
    name: "Hyper Drill",
    power: 100,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  HYPER_VOICE: createSpecialMove("HYPER_VOICE", {
    name: "Hyper Voice",
    power: 90,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  ICE_BEAM: createSpecialMove("ICE_BEAM", {
    name: "Ice Beam",
    power: 90,
    type: PokemonTypes.ICE,
    effect: "Has a 10% chance to freeze the target.",
  }),
  ICE_FANG: createPhysicalMove("ICE_FANG", {
    name: "Ice Fang",
    power: 65,
    type: PokemonTypes.ICE,
    effect:
      "Has a 10% chance to freeze the target and a $effect_chance% chance to make the target flinch.",
  }),
  ICE_PUNCH: createPhysicalMove("ICE_PUNCH", {
    name: "Ice Punch",
    power: 75,
    type: PokemonTypes.ICE,
    effect: "Has a 10% chance to freeze the target.",
  }),
  ICE_SHARD: createPhysicalMove("ICE_SHARD", {
    name: "Ice Shard",
    power: 40,
    type: PokemonTypes.ICE,
    effect: "null",
  }),
  ICE_SPINNER: createPhysicalMove("ICE_SPINNER", {
    name: "Ice Spinner",
    power: 80,
    type: PokemonTypes.ICE,
    effect: "null",
  }),
  ICICLE_CRASH: createPhysicalMove("ICICLE_CRASH", {
    name: "Icicle Crash",
    power: 85,
    type: PokemonTypes.ICE,
    effect: "Has a 30% chance to make the target flinch.",
  }),
  ICICLE_SPEAR: createPhysicalMove("ICICLE_SPEAR", {
    name: "Icicle Spear",
    power: 25,
    type: PokemonTypes.ICE,
    effect: "Hits 2-5 times in one turn.",
  }),
  ICY_WIND: createSpecialMove("ICY_WIND", {
    name: "Icy Wind",
    power: 55,
    type: PokemonTypes.ICE,
    effect: "Has a 100% chance to lower the target's Speed by one stage.",
  }),
  INCINERATE: createSpecialMove("INCINERATE", {
    name: "Incinerate",
    power: 60,
    type: PokemonTypes.FIRE,
    effect: "If the target is holding a Berry, it is burnt and becomes no longer usable.",
  }),
  IRON_DEFENSE: createStatusMove("IRON_DEFENSE", {
    name: "Iron Defense",
    power: null,
    type: PokemonTypes.STEEL,
    effect: "Raises the user's Defense by two stages.",
  }),
  IRON_HEAD: createPhysicalMove("IRON_HEAD", {
    name: "Iron Head",
    power: 80,
    type: PokemonTypes.STEEL,
    effect: "Has a 30% chance to make the target flinch.",
  }),
  IRON_TAIL: createPhysicalMove("IRON_TAIL", {
    name: "Iron Tail",
    power: 100,
    type: PokemonTypes.STEEL,
    effect: "Has a 30% chance to lower the target's Defense by one stage.",
  }),
  KNOCK_OFF: createPhysicalMove("KNOCK_OFF", {
    name: "Knock Off",
    power: 65,
    type: PokemonTypes.DARK,
    effect: "Target drops its held item.",
  }),
  KOWTOW_CLEAVE: createPhysicalMove("KOWTOW_CLEAVE", {
    name: "Kowtow Cleave",
    power: 85,
    type: PokemonTypes.DARK,
    effect: "null",
  }),
  LEAF_BLADE: createPhysicalMove("LEAF_BLADE", {
    name: "Leaf Blade",
    power: 90,
    type: PokemonTypes.GRASS,
    effect: "Has an increased chance for a critical hit.",
  }),
  LEAFAGE: createPhysicalMove("LEAFAGE", {
    name: "Leafage",
    power: 40,
    type: PokemonTypes.GRASS,
    effect: "null",
  }),
  LEECH_LIFE: createPhysicalMove("LEECH_LIFE", {
    name: "Leech Life",
    power: 80,
    type: PokemonTypes.BUG,
    effect:
      "The user drains the target's blood. The user's HP is restored by up to half the damage taken by the target.",
  }),
  LEECH_SEED: createStatusMove("LEECH_SEED", {
    name: "Leech Seed",
    power: null,
    type: PokemonTypes.GRASS,
    effect: "Seeds the target, stealing HP from it every turn.",
  }),
  LEER: createStatusMove("LEER", {
    name: "Leer",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Lowers the target's Defense by one stage.",
  }),
  LICK: createPhysicalMove("LICK", {
    name: "Lick",
    power: 30,
    type: PokemonTypes.GHOST,
    effect: "Has a 30% chance of paralyzing the target.",
  }),
  LIGHT_SCREEN: createStatusMove("LIGHT_SCREEN", {
    name: "Light Screen",
    power: null,
    type: PokemonTypes.PSYCHIC,
    effect: "Reduces damage from special attacks by 50% for five turns.",
  }),
  LIQUIDATION: createPhysicalMove("LIQUIDATION", {
    name: "Liquidation",
    power: 85,
    type: PokemonTypes.WATER,
    effect: "Has a 20% chance to lower the target's Defense by one stage.",
  }),
  LOW_SWEEP: createPhysicalMove("LOW_SWEEP", {
    name: "Low Sweep",
    power: 65,
    type: PokemonTypes.FIGHTING,
    effect:
      "The user makes a swift attack on the target's legs, which lowers the target's Speed stat.",
  }),
  LUMINA_CRASH: createSpecialMove("LUMINA_CRASH", {
    name: "Lumina Crash",
    power: 80,
    type: PokemonTypes.PSYCHIC,
    effect: "null",
  }),
  LUNGE: createPhysicalMove("LUNGE", {
    name: "Lunge",
    power: 80,
    type: PokemonTypes.BUG,
    effect:
      "The user makes a lunge at the target, attacking with full force. This also lowers the target's Attack stat. ",
  }),
  MAGICAL_LEAF: createSpecialMove("MAGICAL_LEAF", {
    name: "Magical Leaf",
    power: 60,
    type: PokemonTypes.GRASS,
    effect: "Never misses.",
  }),
  MAGICAL_TORQUE: createPhysicalMove("MAGICAL_TORQUE", {
    name: "Magical Torque",
    power: 100,
    type: PokemonTypes.FAIRY,
    effect: "null",
  }),
  MEGA_DRAIN: createSpecialMove("MEGA_DRAIN", {
    name: "Mega Drain",
    power: 40,
    type: PokemonTypes.GRASS,
    effect: "Drains half the damage inflicted to heal the user.",
  }),
  METAL_CLAW: createPhysicalMove("METAL_CLAW", {
    name: "Metal Claw",
    power: 50,
    type: PokemonTypes.STEEL,
    effect: "Has a 10% chance to raise the user's Attack by one stage.",
  }),
  METAL_SOUND: createStatusMove("METAL_SOUND", {
    name: "Metal Sound",
    power: null,
    type: PokemonTypes.STEEL,
    effect: "A horrible sound like scraping metal harshly lowers the target's Sp. Def stat.",
  }),
  MOONBLAST: createSpecialMove("MOONBLAST", {
    name: "Moonblast",
    power: 95,
    type: PokemonTypes.FAIRY,
    effect: "Has a 30% chance to lower the target's Special Attack by one stage.",
  }),
  MUD_SLAP: createSpecialMove("MUD_SLAP", {
    name: "Mud-Slap",
    power: 20,
    type: PokemonTypes.GROUND,
    effect: "Has a 100% chance to lower the target's accuracy by one stage.",
  }),
  MUDDY_WATER: createSpecialMove("MUDDY_WATER", {
    name: "Muddy Water",
    power: 90,
    type: PokemonTypes.WATER,
    effect: "Has a 30% chance to lower the target's accuracy by one stage.",
  }),
  MYSTICAL_FIRE: createSpecialMove("MYSTICAL_FIRE", {
    name: "Mystical Fire",
    power: 75,
    type: PokemonTypes.FIRE,
    effect:
      "The user attacks by breathing a special, hot fire. This also lowers the target's Sp. Atk stat. ",
  }),
  NIGHT_SLASH: createPhysicalMove("NIGHT_SLASH", {
    name: "Night Slash",
    power: 70,
    type: PokemonTypes.DARK,
    effect:
      "The user slashes the target the instant an opportunity arises. This move has a heightened chance of landing a critical hit. ",
  }),
  NOXIOUS_TORQUE: createPhysicalMove("NOXIOUS_TORQUE", {
    name: "Noxious Torque",
    power: 100,
    type: PokemonTypes.POISON,
    effect: "null",
  }),
  NUZZLE: createPhysicalMove("NUZZLE", {
    name: "Nuzzle",
    power: 20,
    type: PokemonTypes.ELECTRIC,
    effect: "Has a 100% chance to paralyze the target.",
  }),
  OVERHEAT: createSpecialMove("OVERHEAT", {
    name: "Overheat",
    power: 130,
    type: PokemonTypes.FIRE,
    effect: "Lowers the user's Special Attack by two stages after inflicting damage.",
  }),
  PAYBACK: createPhysicalMove("PAYBACK", {
    name: "Payback",
    power: 50,
    type: PokemonTypes.DARK,
    effect:
      "The user stores power, then attacks. This move's power is doubled if the user moves after the target.",
  }),
  PETAL_BLIZZARD: createPhysicalMove("PETAL_BLIZZARD", {
    name: "Petal Blizzard",
    power: 90,
    type: PokemonTypes.GRASS,
    effect: "null",
  }),
  PHANTOM_FORCE: createPhysicalMove("PHANTOM_FORCE", {
    name: "Phantom Force",
    power: 90,
    type: PokemonTypes.GHOST,
    effect:
      "User vanishes, dodging all attacks, and hits next turn.  Hits through Protect and Detect.",
  }),
  PIN_MISSILE: createPhysicalMove("PIN_MISSILE", {
    name: "Pin Missile",
    power: 25,
    type: PokemonTypes.BUG,
    effect: "Hits 2-5 times in one turn.",
  }),
  PLAY_ROUGH: createPhysicalMove("PLAY_ROUGH", {
    name: "Play Rough",
    power: 90,
    type: PokemonTypes.FAIRY,
    effect: "Has a 10% chance to lower the target's Attack by one stage.",
  }),
  PLUCK: createPhysicalMove("PLUCK", {
    name: "Pluck",
    power: 60,
    type: PokemonTypes.FLYING,
    effect: "If target has a berry, inflicts double damage and uses the berry.",
  }),
  POISON_JAB: createPhysicalMove("POISON_JAB", {
    name: "Poison Jab",
    power: 80,
    type: PokemonTypes.POISON,
    effect: "Has a 30% chance to poison the target.",
  }),
  POUND: createPhysicalMove("POUND", {
    name: "Pound",
    power: 40,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  POWER_GEM: createSpecialMove("POWER_GEM", {
    name: "Power Gem",
    power: 80,
    type: PokemonTypes.ROCK,
    effect: "null",
  }),
  POWER_WHIP: createPhysicalMove("POWER_WHIP", {
    name: "Power Whip",
    power: 120,
    type: PokemonTypes.GRASS,
    effect: "null",
  }),
  PROTECT: createStatusMove("PROTECT", {
    name: "Protect",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Prevents any moves from hitting the user this turn.",
  }),
  PSYCHIC_FANGS: createPhysicalMove("PSYCHIC_FANGS", {
    name: "Psychic Fangs",
    power: 85,
    type: PokemonTypes.PSYCHIC,
    effect: "Destroys Reflect and Light Screen.",
  }),
  PSYCHIC: createSpecialMove(PokemonTypes.PSYCHIC, {
    name: PokemonTypes.PSYCHIC,
    power: 90,
    type: PokemonTypes.PSYCHIC,
    effect: "Has a 10% chance to lower the target's Special Defense by one stage.",
  }),
  PSYCHO_CUT: createPhysicalMove("PSYCHO_CUT", {
    name: "Psycho Cut",
    power: 70,
    type: PokemonTypes.PSYCHIC,
    effect: "Has an increased chance for a critical hit.",
  }),
  QUICK_ATTACK: createPhysicalMove("QUICK_ATTACK", {
    name: "Quick Attack",
    power: 40,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  RAGE_FIST: createPhysicalMove("RAGE_FIST", {
    name: "Rage Fist",
    power: 50,
    type: PokemonTypes.GHOST,
    effect: "null",
  }),
  RAPID_SPIN: createPhysicalMove("RAPID_SPIN", {
    name: "Rapid Spin",
    power: 50,
    type: PokemonTypes.NORMAL,
    effect: "Frees the user from binding moves, removes Leech Seed, and blows away Spikes.",
  }),
  RAZOR_LEAF: createPhysicalMove("RAZOR_LEAF", {
    name: "Razor Leaf",
    power: 55,
    type: PokemonTypes.GRASS,
    effect: "Has an increased chance for a critical hit.",
  }),
  REFLECT: createStatusMove("REFLECT", {
    name: "Reflect",
    power: null,
    type: PokemonTypes.PSYCHIC,
    effect: "Reduces damage from physical attacks by half.",
  }),
  REVELATION_DANCE: createSpecialMove("REVELATION_DANCE", {
    name: "Revelation Dance",
    power: 90,
    type: PokemonTypes.NORMAL,
    effect: "Has the same type as the user.",
  }),
  ROCK_BLAST: createPhysicalMove("ROCK_BLAST", {
    name: "Rock Blast",
    power: 25,
    type: PokemonTypes.ROCK,
    effect: "Hits 2-5 times in one turn.",
  }),
  ROCK_SLIDE: createPhysicalMove("ROCK_SLIDE", {
    name: "Rock Slide",
    power: 75,
    type: PokemonTypes.ROCK,
    effect: "Has a 30% chance to make the target flinch.",
  }),
  ROCK_SMASH: createPhysicalMove("ROCK_SMASH", {
    name: "Rock Smash",
    power: 40,
    type: PokemonTypes.FIGHTING,
    effect: "Has a 50% chance to lower the target's Defense by one stage.",
  }),
  ROCK_THROW: createPhysicalMove("ROCK_THROW", {
    name: "Rock Throw",
    power: 50,
    type: PokemonTypes.ROCK,
    effect: "null",
  }),
  ROCK_TOMB: createPhysicalMove("ROCK_TOMB", {
    name: "Rock Tomb",
    power: 60,
    type: PokemonTypes.ROCK,
    effect: "Has a 100% chance to lower the target's Speed by one stage.",
  }),
  ROUND: createSpecialMove("ROUND", {
    name: "Round",
    power: 60,
    type: PokemonTypes.NORMAL,
    effect:
      "If multiple Pokémon on the same team use it in the same turn, the power doubles to 120 and the slower Pokémon move immediately after the fastest Pokémon uses it, regardless of their Speed.",
  }),
  SAND_ATTACK: createStatusMove("SAND_ATTACK", {
    name: "Sand Attack",
    power: null,
    type: PokemonTypes.GROUND,
    effect: "Lowers the target's accuracy by one stage.",
  }),
  SANDSTORM: createStatusMove("SANDSTORM", {
    name: "Sandstorm",
    power: null,
    type: PokemonTypes.ROCK,
    effect: "Changes the weather to a sandstorm for five turns.",
  }),
  SCRATCH: createPhysicalMove("SCRATCH", {
    name: "Scratch",
    power: 40,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  SCREECH: createStatusMove("SCREECH", {
    name: "Screech",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Lowers the target's Defense by two stages.",
  }),
  SEED_BOMB: createPhysicalMove("SEED_BOMB", {
    name: "Seed Bomb",
    power: 80,
    type: PokemonTypes.GRASS,
    effect: "null",
  }),
  SHADOW_BALL: createSpecialMove("SHADOW_BALL", {
    name: "Shadow Ball",
    power: 80,
    type: PokemonTypes.GHOST,
    effect: "Has a 20% chance to lower the target's Special Defense by one stage.",
  }),
  SHADOW_CLAW: createPhysicalMove("SHADOW_CLAW", {
    name: "Shadow Claw",
    power: 70,
    type: PokemonTypes.GHOST,
    effect: "Has an increased chance for a critical hit.",
  }),
  SHADOW_SNEAK: createPhysicalMove("SHADOW_SNEAK", {
    name: "Shadow Sneak",
    power: 40,
    type: PokemonTypes.GHOST,
    effect: "null",
  }),
  SHELL_SMASH: createStatusMove("SHELL_SMASH", {
    name: "Shell Smash",
    power: null,
    type: PokemonTypes.NORMAL,
    effect:
      "Raises user's Attack, Special Attack, and Speed by two stages.  Lower user's Defense and Special Defense by one stage.",
  }),
  SHIFT_GEAR: createStatusMove("SHIFT_GEAR", {
    name: "Shift Gear",
    power: null,
    type: PokemonTypes.STEEL,
    effect: "Raises the user's Attack by one stage and its Speed by two stages.",
  }),
  SLAM: createPhysicalMove("SLAM", {
    name: "Slam",
    power: 80,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  SLASH: createPhysicalMove("SLASH", {
    name: "Slash",
    power: 70,
    type: PokemonTypes.NORMAL,
    effect: "Has an increased chance for a critical hit.",
  }),
  SLEEP_POWDER: createStatusMove("SLEEP_POWDER", {
    name: "Sleep Powder",
    power: null,
    type: PokemonTypes.GRASS,
    effect: "Puts the target to sleep.",
  }),
  SLUDGE_BOMB: createSpecialMove("SLUDGE_BOMB", {
    name: "Sludge Bomb",
    power: 90,
    type: PokemonTypes.POISON,
    effect: "Has a 30% chance to poison the target.",
  }),
  SLUDGE_WAVE: createSpecialMove("SLUDGE_WAVE", {
    name: "Sludge Wave",
    power: 95,
    type: PokemonTypes.POISON,
    effect: "Has a 10% chance to poison the target.",
  }),
  SLUDGE: createSpecialMove("SLUDGE", {
    name: "Sludge",
    power: 65,
    type: PokemonTypes.POISON,
    effect: "Has a 30% chance to poison the target.",
  }),
  SMOG: createSpecialMove("SMOG", {
    name: "Smog",
    power: 30,
    type: PokemonTypes.POISON,
    effect: "Has a 40% chance to poison the target.",
  }),
  SNARL: createSpecialMove("SNARL", {
    name: "Snarl",
    power: 55,
    type: PokemonTypes.DARK,
    effect: "Has a 100% chance to lower the target's Special Attack by one stage.",
  }),
  SNOWSCAPE: createStatusMove("SNOWSCAPE", {
    name: "Snowscape",
    power: null,
    type: PokemonTypes.ICE,
    effect:
      "The user summons a snowstorm lasting five turns. This boosts the Defense stats of Ice types.",
  }),
  SOLAR_BEAM: createSpecialMove("SOLAR_BEAM", {
    name: "Solar Beam",
    power: 120,
    type: PokemonTypes.GRASS,
    effect: "Requires a turn to charge before attacking.",
  }),
  SPARK: createPhysicalMove("SPARK", {
    name: "Spark",
    power: 65,
    type: PokemonTypes.ELECTRIC,
    effect: "Has a 30% chance to paralyze the target.",
  }),
  SPIN_OUT: createPhysicalMove("SPIN_OUT", {
    name: "Spin Out",
    power: 100,
    type: PokemonTypes.STEEL,
    effect: "null",
  }),
  SPIRIT_BREAK: createPhysicalMove("SPIRIT_BREAK", {
    name: "Spirit Break",
    power: 75,
    type: PokemonTypes.FAIRY,
    effect:
      "The user attacks the target with so much force that it could break the target's spirit. This also lowers the target's Sp. Atk stat.",
  }),
  SPORE: createStatusMove("SPORE", {
    name: "Spore",
    power: null,
    type: PokemonTypes.GRASS,
    effect: "Puts the target to sleep.",
  }),
  STEALTH_ROCK: createStatusMove("STEALTH_ROCK", {
    name: "Stealth Rock",
    power: null,
    type: PokemonTypes.ROCK,
    effect: "Causes damage when opposing Pokémon switch in.",
  }),
  STEEL_ROLLER: createPhysicalMove("STEEL_ROLLER", {
    name: "Steel Roller",
    power: 130,
    type: PokemonTypes.STEEL,
    effect: "null",
  }),
  STOMPING_TANTRUM: createPhysicalMove("STOMPING_TANTRUM", {
    name: "Stomping Tantrum",
    power: 75,
    type: PokemonTypes.GROUND,
    effect: "Has double power if the user's last move failed.",
  }),
  STONE_EDGE: createPhysicalMove("STONE_EDGE", {
    name: "Stone Edge",
    power: 100,
    type: PokemonTypes.ROCK,
    effect: "Has an increased chance for a critical hit.",
  }),
  STRUGGLE_BUG: createSpecialMove("STRUGGLE_BUG", {
    name: "Struggle Bug",
    power: 50,
    type: PokemonTypes.BUG,
    effect: "Has a 100% chance to lower the target's Special Attack by one stage.",
  }),
  SUCKER_PUNCH: createPhysicalMove("SUCKER_PUNCH", {
    name: "Sucker Punch",
    power: 70,
    type: PokemonTypes.DARK,
    effect: "Only works if the target is about to use a damaging move.",
  }),
  SUNNY_DAY: createStatusMove("SUNNY_DAY", {
    name: "Sunny Day",
    power: null,
    type: PokemonTypes.FIRE,
    effect: "Changes the weather to sunny for five turns.",
  }),
  SUPER_FANG: createPhysicalMove("SUPER_FANG", {
    name: "Super Fang",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Inflicts damage equal to half the target's HP.",
  }),
  SWIFT: createSpecialMove("SWIFT", {
    name: "Swift",
    power: 60,
    type: PokemonTypes.NORMAL,
    effect: "Never misses.",
  }),
  TACKLE: createPhysicalMove("TACKLE", {
    name: "Tackle",
    power: 40,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  TAIL_WHIP: createStatusMove("TAIL_WHIP", {
    name: "Tail Whip",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Lowers the target's Defense by one stage.",
  }),
  TAILWIND: createStatusMove("TAILWIND", {
    name: "Tailwind",
    power: null,
    type: PokemonTypes.FLYING,
    effect: "For three turns, friendly Pokémon have doubled Speed.",
  }),
  TAUNT: createStatusMove("TAUNT", {
    name: "Taunt",
    power: null,
    type: PokemonTypes.DARK,
    effect: "For the next few turns, the target can only use damaging moves.",
  }),
  TEETER_DANCE: createStatusMove("TEETER_DANCE", {
    name: "Teeter Dance",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Confuses the target.",
  }),
  TERA_BLAST: createSpecialMove("TERA_BLAST", {
    name: "Tera Blast",
    power: 80,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  THIEF: createPhysicalMove("THIEF", {
    name: "Thief",
    power: 60,
    type: PokemonTypes.DARK,
    effect: "Takes the target's item.",
  }),
  THROAT_CHOP: createPhysicalMove("THROAT_CHOP", {
    name: "Throat Chop",
    power: 80,
    type: PokemonTypes.DARK,
    effect: "Prevents the target from using sound-based moves for two turns.",
  }),
  THUNDER_FANG: createPhysicalMove("THUNDER_FANG", {
    name: "Thunder Fang",
    power: 65,
    type: PokemonTypes.ELECTRIC,
    effect:
      "Has a 10% chance to paralyze the target and a $effect_chance% chance to make the target flinch.",
  }),
  THUNDER_PUNCH: createPhysicalMove("THUNDER_PUNCH", {
    name: "Thunder Punch",
    power: 75,
    type: PokemonTypes.ELECTRIC,
    effect: "Has a 10% chance to paralyze the target.",
  }),
  THUNDER_SHOCK: createSpecialMove("THUNDER_SHOCK", {
    name: "Thunder Shock",
    power: 40,
    type: PokemonTypes.ELECTRIC,
    effect: "Has a 10% chance to paralyze the target.",
  }),
  THUNDER_WAVE: createStatusMove("THUNDER_WAVE", {
    name: "Thunder Wave",
    power: null,
    type: PokemonTypes.ELECTRIC,
    effect: "Paralyzes the target.",
  }),
  THUNDER: createSpecialMove("THUNDER", {
    name: "Thunder",
    power: 110,
    type: PokemonTypes.ELECTRIC,
    effect: "Has a 30% chance to paralyze the target.",
  }),
  THUNDERBOLT: createSpecialMove("THUNDERBOLT", {
    name: "Thunderbolt",
    power: 90,
    type: PokemonTypes.ELECTRIC,
    effect: "Has a 10% chance to paralyze the target.",
  }),
  TORCH_SONG: createSpecialMove("TORCH_SONG", {
    name: "Torch Song",
    power: 80,
    type: PokemonTypes.FIRE,
    effect: "Inflicts regular damage.  Raises the user's Special Attack by one stage.",
  }),
  TORMENT: createStatusMove("TORMENT", {
    name: "Torment",
    power: null,
    type: PokemonTypes.DARK,
    effect: "Prevents the target from using the same move twice in a row.",
  }),
  TOXIC: createStatusMove("TOXIC", {
    name: "Toxic",
    power: null,
    type: PokemonTypes.POISON,
    effect: "Badly poisons the target, inflicting more damage every turn.",
  }),
  TRAILBLAZE: createPhysicalMove("TRAILBLAZE", {
    name: "Trailblaze",
    power: 50,
    type: PokemonTypes.GRASS,
    effect: "null",
  }),
  TRI_ATTACK: createSpecialMove("TRI_ATTACK", {
    name: "Tri Attack",
    power: 80,
    type: PokemonTypes.NORMAL,
    effect: "Has a 20% chance to burn, freeze, or paralyze the target.",
  }),
  VENOSHOCK: createSpecialMove("VENOSHOCK", {
    name: "Venoshock",
    power: 65,
    type: PokemonTypes.POISON,
    effect: "Inflicts double damage if the target is Poisoned.",
  }),
  VISE_GRIP: createPhysicalMove("VISE_GRIP", {
    name: "Vise Grip",
    power: 55,
    type: PokemonTypes.NORMAL,
    effect: "null",
  }),
  WATER_GUN: createSpecialMove("WATER_GUN", {
    name: "Water Gun",
    power: 40,
    type: PokemonTypes.WATER,
    effect: "null",
  }),
  WATER_PULSE: createSpecialMove("WATER_PULSE", {
    name: "Water Pulse",
    power: 60,
    type: PokemonTypes.WATER,
    effect: "Has a 20% chance to confuse the target.",
  }),
  WICKED_TORQUE: createPhysicalMove("WICKED_TORQUE", {
    name: "Wicked Torque",
    power: 80,
    type: PokemonTypes.DARK,
    effect: "null",
  }),
  WILL_O_WISP: createStatusMove("WILL_O_WISP", {
    name: "Will-O-Wisp",
    power: null,
    type: PokemonTypes.FIRE,
    effect: "Burns the target.",
  }),
  WING_ATTACK: createPhysicalMove("WING_ATTACK", {
    name: "Wing Attack",
    power: 60,
    type: PokemonTypes.FLYING,
    effect: "null",
  }),
  WOOD_HAMMER: createPhysicalMove("WOOD_HAMMER", {
    name: "Wood Hammer",
    power: 120,
    type: PokemonTypes.GRASS,
    effect: "User receives 1/3 the damage inflicted in recoil.",
  }),
  WORK_UP: createStatusMove("WORK_UP", {
    name: "Work Up",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Raises the user's Attack and Special Attack by one stage.",
  }),
  WRAP: createPhysicalMove("WRAP", {
    name: "Wrap",
    power: 15,
    type: PokemonTypes.NORMAL,
    effect: "Prevents the target from fleeing and inflicts damage for 2-5 turns.",
  }),
  X_SCISSOR: createPhysicalMove("X_SCISSOR", {
    name: "X-Scissor",
    power: 80,
    type: PokemonTypes.BUG,
    effect: "null",
  }),
  YAWN: createStatusMove("YAWN", {
    name: "Yawn",
    power: null,
    type: PokemonTypes.NORMAL,
    effect: "Target sleeps at the end of the next turn.",
  }),
  ZEN_HEADBUTT: createPhysicalMove("ZEN_HEADBUTT", {
    name: "Zen Headbutt",
    power: 80,
    type: PokemonTypes.PSYCHIC,
    effect: "Has a 20% chance to make the target flinch.",
  }),
})
